package tools.scrapers.lanyrd

import tools.utils.ScraperTest
import tools.utils.Scraper
import tools.scrapers.lanyrd.models.LanyrdEvent
import tools.scrapers.lanyrd.models.LanyrdAddress
import play.api.libs.json.Json

object LanyrdScraperTest extends ScraperTest[LanyrdEvent] {
  private val emptyEvent = LanyrdEvent("", "", None, None, "", "", LanyrdAddress("", "", "", "", "", ""), "", "", List(), "")
  val scraper: Scraper[LanyrdEvent] = LanyrdScraper
  val tests: Map[String, LanyrdEvent] = Map(
    "http://lanyrd.com/2015/agilefrance/" -> Json.parse("""{"name":"Agile France 2015","descriptionHTML":"<p>Depuis dix ans, cette conférence se construit avec les praticiens des méthodes agiles.</p> \n<p>En 2015, nous pensons que le temps est venu de questionner nos croyances, de déconstruire nos pratiques, d'examiner nos fondamentaux, d'interroger nos limites, et d'explorer d'autres approches.</p>","start":1434578400000,"end":1434664800000,"websiteUrl":"http://conference-agile.fr/","scheduleUrl":"","address":{"name":"Chalet de la Porte Jaune","street":"Avenue de Nogent","city":"Paris","country":"France","url":"http://lanyrd.com/venues/paris/vdhqg/","gmap":"http://maps.google.com/maps?q=Chalet%20de%20la%20Porte%20Jaune@48.8384423521,2.45936883946"},"twitterAccountUrl":"http://twitter.com/AgileFrance","twitterHashtagUrl":"https://twitter.com/#!/search/%23AgileFrance","tags":["Agile","Kanban","learning organisations","people","Scrum","Software Development"],"url":"http://lanyrd.com/2015/agilefrance/"}""").asOpt[LanyrdEvent].getOrElse(emptyEvent),
    "http://lanyrd.com/2015/varnishsoftware/" -> Json.parse("""{"name":"Varnish Summit Paris","descriptionHTML":"<p>Join us in scaling the heights, explore all things Varnish and learn what makes some of the world's most influential websites fly. Varnish Software Summits will deliver words from Varnish core developers and customers, special guest speakers, networking opportunities, lunch and refreshments.</p>","start":1443045600000,"end":1443045600000,"websiteUrl":"https://www.eventbrite.com/e/varnish-summit-paris-tickets-17098692650","scheduleUrl":"https://varnishsummitparis2015.sched.org/","address":{"name":"Centre de Conférence Paris Victoire","street":"52 rue de la Victoire, 75009 - With public transportation you can take the subway line 12 until station 'Notre-Dame-de-Lorette', or line 7 until station 'Le Peletier'.","city":"Paris","country":"France","url":"http://lanyrd.com/venues/paris/vcwtb/","gmap":"http://maps.google.com/maps?q=48.8753835,2.3350875+(Centre de Conférence Paris Victoire)"},"twitterAccountUrl":"http://twitter.com/varnishsoftware","twitterHashtagUrl":"https://twitter.com/#!/search/%23varnishsummit","tags":["API","cache","High Availability","SSL/TLS","Traffic analysis","Varnish","Web Performance"],"url":"http://lanyrd.com/2015/varnishsoftware/"}""").asOpt[LanyrdEvent].getOrElse(emptyEvent),
    "http://lanyrd.com/2015/le-futur-du-gaming-realite-virtuelle-jeu-immersi-2/" -> Json.parse("""{"name":"Le Futur du Gaming : réalité virtuelle, jeu immersif, contrôles corporels & audio","descriptionHTML":"Rendez-vous pour un meetup spécial jeux vidéo. Au menu, 3 confs dédiées au gaming et à la réalité virtuelle grâce à la techno Intel® RealSense™. Vous travaillez aussi sur des expérimentations dans votre garage ? Faites-en la démo autour de pizzas!","start":1442268000000,"end":1442268000000,"websiteUrl":"http://bit.ly/1E9xP9m","scheduleUrl":"","address":{"name":"ISART Digital","street":"2, rue de la roquete, 75011","city":"Paris","country":"France","url":"http://lanyrd.com/venues/paris/vdtc/","gmap":"http://maps.google.com/maps?q=48.8532891253,2.37215615616+(ISART Digital)"},"twitterAccountUrl":"","twitterHashtagUrl":"","tags":[],"url":"http://lanyrd.com/2015/le-futur-du-gaming-realite-virtuelle-jeu-immersi-2/"}""").asOpt[LanyrdEvent].getOrElse(emptyEvent))
}