package tools.scrapers.eventseye

import tools.utils.ScraperTest
import tools.utils.Scraper
import tools.scrapers.eventseye.models.EventsEyeEvent
import tools.scrapers.eventseye.models.EventsEyeVenue
import tools.scrapers.eventseye.models.EventsEyeAddress
import play.api.libs.json.Json

object EventsEyeScraperTest extends ScraperTest[EventsEyeEvent] {
  private val emptyEvent = EventsEyeEvent("", "", List(), "", "", "", None, List(), EventsEyeVenue("", "", EventsEyeAddress("", "", "", "", ""), "", "", ""), List(), None, "", "", "", "")
  val scraper: Scraper[EventsEyeEvent] = EventsEyeScraper
  val tests: Map[String, EventsEyeEvent] = Map(
    "http://www.eventseye.com/fairs/f-top-ingenieurs-7880-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/top-ingenieurs-7880-1.gif","name":"TOP INGÉNIEURS 2015","industries":["Employment","Education & Training"],"decription":"Event dedicated to Engineers, Scientists & IT Professionals","audience":"Trade & General Public","cycle":"twice a year","nextDate":1443650400000,"otherDates":[1456786800000,1475272800000],"venue":{"logo":"http://www.eventseye.com/l/paris-1391-1.gif","name":"Espace Grande Arche","address":{"name":"Parvis de la Défense","complement":"","street":"92044 Paris la Défense 7 Cedex","city":"","country":"France"},"phone":"+33 (0)1 40.68.22.22","website":"http://www.viparis.com","email":""},"orgas":[{"logo":"http://www.eventseye.com/o/o1400.gif","name":"CNISF (Conseil national des ingénieurs et scientifiques de France)","address":{"name":"7, rue Lamennais","complement":"","street":"","city":"75008 Paris","country":"France"},"phone":"+33 (0)1 44 13 66 88","website":"http://www.cnisf.org","email":"dameline@cnisf.org"},{"logo":"http://www.eventseye.com/o/o2758.gif","name":"Emploi-Pro","address":{"name":"Antony Parc 2 ","complement":"10, place du Général de Gaulle","street":"","city":"92160 Antony","country":"France"},"phone":"","website":"http://www.usinenouvelle.com/emploi/","email":""}],"website":"http://www.saloningenieurs.com","email":"dameline@cnisf.org","phone":"","url":"http://www.eventseye.com/fairs/f-top-ingenieurs-7880-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-expobois-865-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/expobois-865-1.gif","name":"EXPOBOIS 2016","industries":["Machines-tools - Tools","Wood Working Industries"],"decription":"International Exhibition of Woodworking Machinery Manufacturers and Timber Industries","audience":"Trade Public","cycle":"every 2 years","nextDate":1477954800000,"otherDates":[],"venue":{"logo":"http://www.eventseye.com/l/paris-11-1.jpg","name":"Paris Nord Villepinte","address":{"name":"","complement":"","street":"95970 Roissy Cedex","city":"","country":"France"},"phone":"+33 (0)1 40 68 22 22","website":"http://www.viparis.com","email":"communication@viparis.com"},"orgas":[{"logo":"http://www.eventseye.com/o/o152.gif","name":"Symop (Syndicat des entreprises de technologies de production)","address":{"name":"Maison de la Mécanique","complement":"45, rue Louis Blanc","street":"","city":"92038 Paris-La-Défense cedex","country":"France"},"phone":"+33 (0)1 47 17 67 17","website":"http://www.symap.com","email":"expocom@symap.com"},{"logo":"http://www.eventseye.com/o/o1.gif","name":"Comexposium","address":{"name":"Immeuble le Wilson","complement":"70, avenue du Général-de-Gaulle","street":"","city":"92058 Paris-La Défense","country":"France"},"phone":"+33 (0)1 76 77 11 11","website":"http://www.comexposium.com","email":"info@comexposium.com"}],"attendance":{"year":"2004","exponents":"21510","visitors":"?","exhibitionSpace":"?"},"website":"http://www.expobois.fr","email":"expobois@comexpo-paris.com","phone":"","url":"http://www.eventseye.com/fairs/f-expobois-865-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-sitl-solutions-logistiques-2515-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/sitl-solutions-logistiques-2515-1.gif","name":"SITL SOLUTIONS LOGISTIQUES 2016","industries":["Logistics & Transportation Engineering - Handling Operations - Storage","Decision Helping Tools & Management Services"],"decription":"International Week of Transport and Logistics. For the international community of transporters of freight and logistics service providers, SITL offers access to innovative products and services dedicated to procurement, distribution and the supply chain","audience":"Trade Public","cycle":"once a year","nextDate":1458601200000,"otherDates":[1488322800000],"venue":{"logo":"http://www.eventseye.com/l/paris-11-1.jpg","name":"Paris Nord Villepinte","address":{"name":"","complement":"","street":"95970 Roissy Cedex","city":"","country":"France"},"phone":"+33 (0)1 40 68 22 22","website":"http://www.viparis.com","email":"communication@viparis.com"},"orgas":[{"logo":"http://www.eventseye.com/o/o76.gif","name":"Reed Expositions France","address":{"name":"52-54, quai de Dion-Bouton ","complement":"CS 80001","street":"","city":"92806 Puteaux Cedex","country":"France"},"phone":"+33 (0)1 47 56 50 00","website":"http://www.reedexpo.fr","email":"info@reedexpo.fr"},{"logo":"http://www.eventseye.com/o/o12.gif","name":"Reed Exhibitions Companies","address":{"name":"Gateway House","complement":"28 The Quadrant","street":"Richmond, Surrey","city":"TW9 1DN","country":"UK - United Kingdom"},"phone":"+44 20 8271 2134","website":"http://www.reedexpo.com","email":"rxinfo@reedexpo.co.uk"}],"website":"http://www.sitl.eu","email":"info@sitl.eu","phone":"","url":"http://www.eventseye.com/fairs/f-sitl-solutions-logistiques-2515-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-congres-international-de-metrologie-503-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/congres-international-de-metrologie-503-1.gif","name":"CONGRES INTERNATIONAL DE METROLOGIE 2015","industries":["Measurement & Testing","Quality & Maintenance"],"decription":"International Metrology Congress","audience":"Trade Public","cycle":"every 2 years","nextDate":1442786400000,"otherDates":[],"venue":{"logo":"http://www.eventseye.com/l/paris-1-1.jpg","name":"Paris Expo Porte de Versailles","address":{"name":"1, place de la Porte de Versailles","complement":"","street":"75015 Paris","city":"","country":"France"},"phone":"+33 (0)1 40 68 22 22","website":"http://www.viparis.com","email":"commercial@viparis.com"},"orgas":[{"logo":"http://www.eventseye.com/o/o237.gif","name":"Collège Français de Métrologie","address":{"name":"1, rue Gaston Boissier","complement":"","street":"","city":"75015 Paris","country":"France"},"phone":"","website":"http://www.cfmetrologie.com","email":"info@cfmetrologie.com"}],"website":"http://www.metrologie2015.com","email":"info@cfmetrologie.com","phone":"","url":"http://www.eventseye.com/fairs/f-congres-international-de-metrologie-503-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-aps-alarmes-protection-securite-65-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/aps-alarmes-protection-securite-65-1.gif","name":"APS - ALARMES PROTECTION SECURITE 2015","industries":["Security - Risk Management","Home Exhibitions"],"decription":"Specialized Safety & Security Exhibition","audience":"Trade Public","cycle":"every 2 years","nextDate":1443477600000,"otherDates":[],"venue":{"logo":"http://www.eventseye.com/l/paris-1-1.jpg","name":"Paris Expo Porte de Versailles","address":{"name":"1, place de la Porte de Versailles","complement":"","street":"75015 Paris","city":"","country":"France"},"phone":"+33 (0)1 40 68 22 22","website":"http://www.viparis.com","email":"commercial@viparis.com"},"orgas":[{"logo":"http://www.eventseye.com/o/o76.gif","name":"Reed Expositions France","address":{"name":"52-54, quai de Dion-Bouton ","complement":"CS 80001","street":"","city":"92806 Puteaux Cedex","country":"France"},"phone":"+33 (0)1 47 56 50 00","website":"http://www.reedexpo.fr","email":"info@reedexpo.fr"},{"logo":"http://www.eventseye.com/o/o12.gif","name":"Reed Exhibitions Companies","address":{"name":"Gateway House","complement":"28 The Quadrant","street":"Richmond, Surrey","city":"TW9 1DN","country":"UK - United Kingdom"},"phone":"+44 20 8271 2134","website":"http://www.reedexpo.com","email":"rxinfo@reedexpo.co.uk"}],"attendance":{"year":"2005","exponents":"167","visitors":"5576","exhibitionSpace":"?"},"website":"http://www.salon-aps.com","email":"beatrice.panizza@reedexpo.fr","phone":"","url":"http://www.eventseye.com/fairs/f-aps-alarmes-protection-securite-65-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent))
}