package tools.scrapers.eventseye

import tools.utils.ScraperTest
import tools.utils.Scraper
import tools.scrapers.eventseye.models.EventsEyeEvent
import play.api.libs.json.Json

object EventsEyeScraperTest extends ScraperTest[EventsEyeEvent] {
  private val emptyEvent = EventsEyeEvent("", "", "", "", "", "", List(), "", List(), None, "", "", "", "")
  val scraper: Scraper[EventsEyeEvent] = EventsEyeScraper
  val tests: Map[String, EventsEyeEvent] = Map(
    "http://www.eventseye.com/fairs/f-expobois-865-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/expobois-865-1.gif","name":"EXPOBOIS 2016","decription":"International Exhibition of Woodworking Machinery Manufacturers and Timber Industries","audience":"Trade Public","cycle":"every 2 years","nextDate":"01/11/2016","otherDates":[],"venue":"Paris Nord Villepinte","orgas":[{"name":"Symop (Syndicat des entreprises de technologies de production)","address":{"name":"Maison de la Mécanique","complement":"45, rue Louis Blanc","street":"","city":"92038 Paris-La-Défense cedex","country":"France"},"phone":"+33 (0)1 47 17 67 17","site":"http://www.symap.com","email":"expocom@symap.com"},{"name":"Comexposium","address":{"name":"Immeuble le Wilson","complement":"70, avenue du Général-de-Gaulle","street":"","city":"92058 Paris-La Défense","country":"France"},"phone":"+33 (0)1 76 77 11 11","site":"http://www.comexposium.com","email":"info@comexposium.com"}],"attendance":{"year":"2004","exponents":"21510","visitors":"?","exhibitionSpace":"?"},"website":"http://www.expobois.fr","email":"expobois@comexpo-paris.com","phone":"","url":"http://www.eventseye.com/fairs/f-expobois-865-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-sitl-solutions-logistiques-2515-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/sitl-solutions-logistiques-2515-1.gif","name":"SITL SOLUTIONS LOGISTIQUES 2016","decription":"International Week of Transport and Logistics. For the international community of transporters of freight and logistics service providers, SITL offers access to innovative products and services dedicated to procurement, distribution and the supply chain","audience":"Trade Public","cycle":"once a year","nextDate":"22/03/2016","otherDates":["01/03/2017"],"venue":"Paris Nord Villepinte","orgas":[{"name":"Reed Expositions France","address":{"name":"52-54, quai de Dion-Bouton ","complement":"CS 80001","street":"","city":"92806 Puteaux Cedex","country":"France"},"phone":"+33 (0)1 47 56 50 00","site":"http://www.reedexpo.fr","email":"info@reedexpo.fr"},{"name":"Reed Exhibitions Companies","address":{"name":"Gateway House","complement":"28 The Quadrant","street":"Richmond, Surrey","city":"TW9 1DN","country":"UK - United Kingdom"},"phone":"+44 20 8271 2134","site":"http://www.reedexpo.com","email":"rxinfo@reedexpo.co.uk"}],"website":"http://www.sitl.eu","email":"info@sitl.eu","phone":"","url":"http://www.eventseye.com/fairs/f-sitl-solutions-logistiques-2515-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-congres-international-de-metrologie-503-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/congres-international-de-metrologie-503-1.gif","name":"CONGRES INTERNATIONAL DE METROLOGIE 2015","decription":"International Metrology Congress","audience":"Trade Public","cycle":"every 2 years","nextDate":"21/09/2015","otherDates":[],"venue":"Paris Expo Porte de Versailles","orgas":[{"name":"Collège Français de Métrologie","address":{"name":"1, rue Gaston Boissier","complement":"","street":"","city":"75015 Paris","country":"France"},"phone":"","site":"http://www.cfmetrologie.com","email":"info@cfmetrologie.com"}],"website":"http://www.metrologie2015.com","email":"info@cfmetrologie.com","phone":"","url":"http://www.eventseye.com/fairs/f-congres-international-de-metrologie-503-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent),
    "http://www.eventseye.com/fairs/f-aps-alarmes-protection-securite-65-1.html" -> Json.parse("""{"logo":"http://www.eventseye.com/s/aps-alarmes-protection-securite-65-1.gif","name":"APS - ALARMES PROTECTION SECURITE 2015","decription":"Specialized Safety & Security Exhibition","audience":"Trade Public","cycle":"every 2 years","nextDate":"29/09/2015","otherDates":[],"venue":"Paris Expo Porte de Versailles","orgas":[{"name":"Reed Expositions France","address":{"name":"52-54, quai de Dion-Bouton ","complement":"CS 80001","street":"","city":"92806 Puteaux Cedex","country":"France"},"phone":"+33 (0)1 47 56 50 00","site":"http://www.reedexpo.fr","email":"info@reedexpo.fr"},{"name":"Reed Exhibitions Companies","address":{"name":"Gateway House","complement":"28 The Quadrant","street":"Richmond, Surrey","city":"TW9 1DN","country":"UK - United Kingdom"},"phone":"+44 20 8271 2134","site":"http://www.reedexpo.com","email":"rxinfo@reedexpo.co.uk"}],"attendance":{"year":"2005","exponents":"167","visitors":"5576","exhibitionSpace":"?"},"website":"http://www.salon-aps.com","email":"beatrice.panizza@reedexpo.fr","phone":"","url":"http://www.eventseye.com/fairs/f-aps-alarmes-protection-securite-65-1.html"}""").asOpt[EventsEyeEvent].getOrElse(emptyEvent))
}